#!/bin/sh
mkdir -p "$HOME/.local/share/fonts"
export SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

reload_fonts=false
cd "$SCRIPTPATH" || exit

# check that every font in this directory is installed 
# if not copy it to the local font path
for f in *.ttf
do 
  font="${HOME}/.local/share/fonts/${f}"
  [ ! -f "$font" ] &&\
      echo "$font needs install." && cp "$f" "$font" && reload_fonts=true
done


# if any font is installed update the cache
[ $reload_fonts = "true" ] && fc-cache -f -v

exit 0
