#!/bin/sh

SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/down.jpg
fi

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

pkill compton 
pkill picom 
pkill polybar
pkill dunst
pkill lxsession

