#!/bin/sh
SCRIPTPATH="$(cd "$(dirname "$0")" || exit; pwd -P)"
export SCRIPTPATH


# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s "${SCRIPTPATH}"/down /tmp/leftwm-theme-down

# Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

# Make sure all fonts needed are installed
"${SCRIPTPATH}"/fonts/install_fonts

# Boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
    (picom --experimental-backends >/dev/null 2>&1) & 
elif [ -x "$(command -v compton)" ]; then
    (compton >/dev/null 2 >& 1) & 
fi

#set background
if [ -x "$(command -v nitrogen)" ]; then
    nitrogen --restore &
fi

# extras
# Start polybar for each monitor.
cd "${SCRIPTPATH}"/polybar || exit
polybar -m | sed 's/:.*//' | tac | while read -r monitor
do 
  monitor=$monitor polybar -c config.ini main > /dev/null 2>& 1 &
done

